In [1]:
# 1. Import the Numpy package under the name np
import numpy as np

In [4]:
# 2.Create a null vector of size 10
import numpy as np
k = np.zeros(10)
print(k)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#3.Create a null vector of size 10 but the fifth value which is 1
k = np.zeros(10)
k[4]=1
print(k)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#4.Create a vector with values ranging from 10 to 49
m=np.arange(10,50)
print(m)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#5. Reverse a vector (the first element becomes last)
m[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [19]:
#6. Create a 3x3 matrix with values ranging from 0 to 8
I=np.arange(0,9).reshape(3,3)

In [20]:
print(I)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
#7.Find indices of non­zero elements from [1,2,0,0,4,0]
x=[1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

In [22]:
#8.Create a 3x3x3 array with random values
A = np.random.random((3,3,3))
print(A)

[[[0.06475426 0.49143748 0.51031641]
  [0.81855537 0.25023759 0.16344408]
  [0.70035912 0.76074049 0.77718832]]

 [[0.78636174 0.0482959  0.15305538]
  [0.74278288 0.64516528 0.45357358]
  [0.89473852 0.22332841 0.05767557]]

 [[0.79429782 0.59415511 0.17683885]
  [0.4945428  0.73399455 0.75085187]
  [0.76173575 0.56349055 0.33125378]]]


In [30]:
 # 9.Create a random vector of size 30 and find the mean value
B = np.random.random(30)
B.mean()

0.521101502040645

In [32]:
#10. Create a 2d array with 1 on the border and 0 inside
c = np.ones((5,5))
print("Original array:")
print(c)
print("1 on the border and 0 inside in the array")
c[1:-1,1:-1] = 0
print(c)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
# 11.Create an 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
d = np.ones((3,3))
print(" printing Checkerboard pattern:")
d = np.zeros((8,8),dtype=int)
d[1::2,::2] = 1
d[::2,1::2] = 1
print(d)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [34]:
#12. What is the major difference between sets, lists, tuples and dictionaries?
Lists: Its Elements are written inside square brackets
        Repetations of elements are allowed
        
Tuples: Its Elements are written inside normal brackets
        Repetations of elements are not allowed 
        
Dictionaries: Its Elements are written inside curly brackets
              Repetations of elements are not allowed       

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 13. Print first 10 natural numbers using while loop

i=1
while(i<=10):
    i=i+1
    print(i)

In [ ]:
# 14. Print the numbers -10 to -1 using for loop

print(" printing numbers from -10 to -1")
for i in range(-10,0,1):
    print(i)

In [ ]:
# 15. Print the message “Done” after successful execution of any for a loop
k=int(input("enter the table want, "))
for i in range(1,11):
    print(k ,'X',i,'=',k*i)
print('Done') 

In [ ]:
# 16. Create a random vector of size 10 and sort it
o=np.random.random(10)
o.sort()
print(o)  


In [ ]:
#17. Execute any three math functions using NumPy.
import numpy as np
a = np.array([0,30.3,45.5,60,90]) 
c=np.ceil(a)
d=np.floor(a)
f=np.sum(a)
print(c)
print(d)
print(f)